### PR TITLE
Obp parser

### PR DESCRIPTION
**Pull request by freemin7**
- [ ] Integrate into something something CMAKE or stuff
- [ ] Add to file handling code path
- [ ] Make sure it actually builds
- [ ] Verify objoff has right sign by solving the file 
```
min: 3 ~x1
``` 
and getting objective 0 and 
```
min: 3 ~x1
~x1 >= 1
```
and getting objective 3 and
```
min: 3 x1
x1 >= 1
```
and getting objective 3
- [ ] Make that it so fractional values are allowed (and default) instead of forbidding them 
- [ ] Add test instances

I will need some help with 1, 2, 5. If 2 is done but something fails, i am going to fix the code.

### CODE REVIEW

**Comment by freemin7** [comment]
See #15

**Comment by fschloesser** [comment]
Something is wrong here, are you sure you did the rebase correctly onto the develop branch? The pull request should not be affecting the version in `CMakeLists.txt` like it does at the moment.

**Comment by freemin7** [comment]
I am not sure at all. I tried. I can try again. I am not even sure how i would revert though.

**Comment by fschloesser** [comment]
I created a new branch OBP_Parser_based_on_develop off of yours that is rebased on develop, can you allow me to push to your fork?

**Comment by freemin7** [comment]
I don't particularly care about the git history. How about we just take the finished file from my branch and add that to a known good branch?

**Comment by fschloesser** [comment]
It seems I cannot push still.
Since you are just adding a file, your solution should also work: Just create a new branch off of develop and check in your file.

**Comment by freemin7** [comment]
Gute Nacht! I will look into that tomorrow. 

I think i found my error which led to the mess. I assumed that develop is strictly ahead of master, so i just appended the changes i made to master, to develop while at the same time you bumped the `PAPILO_VERSION_PATCH` leading to my patch including the new version bump when i ported all changes to master over to develop.

**Comment by fschloesser** [comment]
You let us know if you need further assistance? I like the idea of just taking a copy of your file and then resetting the branch to add it in a single commit. You could then force push it (it's on your own fork anyway)

**Pull request closed without merging**
